siteTitle="Griddle"
baseColor = "#512DA8"
linkPrefix = "/gatsby-starter-documentation"
docPages = [
  "/docs/",
  "/docs/architecture/",
  "/docs/customization/",
  "/docs/styles/",
  "/docs/plugins/",
  "/docs/api/",
]

examplePages = [
  "/examples/controlling-griddle/",
  "/examples/asList/",
  "/examples/asMap/",
]
