siteTitle="Griddle"
baseColor = "#512DA8"
linkPrefix = "/Griddle"
docPages = [
  "/docs/",
  "/docs/architecture/",
  "/docs/customization/",
  "/docs/styles/",
  "/docs/plugins/",
  "/docs/pluginList/",
  "/docs/api/",
]

examplePages = [
  "/examples/controlling-griddle/",
  "/examples/asList/",
  "/examples/asMap/",
  "/examples/defaultSort/",
  "/examples/nestedData/",
  "/examples/getDataFromRowIntoCell/",
]
