siteTitle="Griddle"
baseColor = "#512DA8"
linkPrefix = "/gatsby-starter-documentation"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/architecture/",
  "/docs/customization/",
  "/docs/controlling-griddle/",
  "/docs/styles/"
]
